### ISSUE TITLE
Texture issue 

### ISSUE THREAD

**Issue by deadscion** [monatann/Gregtania6-Skyblock#1]
I downloaded your mod pack to try out anyway. The frst thing Minecraft complained about was Not Enough items mod missing. I added the mod and restarted the pack.
Minecraft crashed and left this log, but no crash log. 
https://www.dropbox.com/s/0nhekylznmdaog5/latest.log?dl=0

**Comment by monatann** [comment]
I found some bugs in DepLoader(This is downloading modified mods function) and I fixed just now.
Please wait for next release.

v1.0.0 version needs re-start minecraft, but next v1.0.1 fix this problem.
